let instructionImages = {
  1: 'images/handsOnKeyboard6.png',
  2: 'images/task_numbers.png',
  3: 'images/tm_1_cm_1_parity.png',
  4: 'images/tm_1_cm_1_magnitude.png',
  5: 'images/tm_2_cm_1_parity.png',
  6: 'images/tm_2_cm_1_magnitude.png',
  7: 'images/tm_3_cm_1_parity.png',
  8: 'images/tm_3_cm_1_magnitude.png',
  9: 'images/tm_4_cm_1_parity.png',
  10: 'images/tm_4_cm_1_magnitude.png',
  11: 'images/tm_1_cm_2_parity.png',
  12: 'images/tm_1_cm_2_magnitude.png',
  13: 'images/tm_2_cm_2_parity.png',
  14: 'images/tm_2_cm_2_magnitude.png',
  15: 'images/tm_3_cm_2_parity.png',
  16: 'images/tm_3_cm_2_magnitude.png',
  17: 'images/tm_4_cm_2_parity.png',
  18: 'images/tm_4_cm_2_magnitude.png'
}
